### ISSUE TITLE
[bug] Version magic mismatch

### ISSUE THREAD

**Issue by telans** [LWSS/Cartographer#1]
`[telans@desktop Cartographer]$ make`
`make -C /lib/modules/5.1.7-arch1-1-ARCH/build M=/home/telans/Documents/coding/Cartographer modules`
`make[1]: warning: jobserver unavailable: using -j1.  Add '+' to parent make rule.`
`make[1]: Entering directory '/usr/lib/modules/5.1.7-arch1-1-ARCH/build'`
`  Building modules, stage 2.`
`  MODPOST 1 modules`
`make[1]: Leaving directory '/usr/lib/modules/5.1.7-arch1-1-ARCH/build'`

`[telans@desktop Cartographer]$ sudo insmod cartographer.ko `
`[sudo] password for telans: `
`insmod: ERROR: could not insert module cartographer.ko: Invalid module format`

`[telans@desktop Cartographer]$ uname -r`
`5.1.7-arch1-1-ARCH`

journald output from insmod:

`cartographer: version magic '5.1.6-arch1-1-ARCH SMP preempt mod_unload ' should be '5.1.7-arch1-1-ARCH SMP preempt mod_unload '`

There are a few places online which mention other kernel configurations, but it seems I have all of them active within the arch kernel anyways.
https://devtalk.nvidia.com/default/topic/921545/jetson-tx1/version-magic-does-not-match-in-kernel-module/post/5279374/#5279374
https://stackoverflow.com/a/55937906

linux-headers are up to date with kernel. 

To be clear, the previous kernel/headers worked perfectly, it just seems to be some version number stuck somewhere and I'm not too sure how to fix it.

Cheers

**Comment by LWSS** [comment]
have you rebooted recently?

**Comment by telans** [comment]
I have a few times, as well as reinstalled kernel/headers

**Comment by telans** [comment]
Managed to fix it just with `make clean` then `make`... Really should've tried that first

I assume make pulls some version info from tmp_versions/cartographer.mod?

cartographer.ko info:
old: [119] vermagic=5.1.6-arch1-1-ARCH SMP preempt mod_unload
new: [119] vermagic=5.1.7-arch1-1-ARCH SMP preempt mod_unload

Cheers
