### ISSUE TITLE
Doesn't work with linux-zen kernel

### ISSUE THREAD

**Issue by Zeldern** [LWSS/Cartographer#5]
insmod: ERROR: could not insert module cartographer.ko: Invalid parameters
[ 1270.335828] cartographer: ftrace_set_filter_ip() failed: -22

**Comment by LWSS** [comment]
more info? 

kernel version, build flags, linux-zen? would be nice

**Comment by Zeldern** [comment]
Its from the arch repos. The same kernel (5.4.6) non "zen" version works fine however.

5.4.6.zen3-1
config: https://git.archlinux.org/svntogit/packages.git/tree/trunk/config?h=packages/linux-zen
https://www.archlinux.org/packages/extra/x86_64/linux-zen/
https://github.com/zen-kernel/zen-kernel/tree/v5.4.6-zen3

**Comment by LWSS** [comment]
did you make sure to make clean before you tried to build it again for the new kernel?

**Comment by Zeldern** [comment]
Yeah i did, the result was still the same.
